let allPlansMealData = {
  vegBasic: {
    mon: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    tues: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    wed: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    thurs: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    friday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    saturday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    sunday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
  },

  vegPremium: {
    mon: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    tues: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    wed: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    thurs: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    friday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    saturday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
    sunday: {
      breakfast: [],
      lunch: [],
      dinner: [],
    },
  },
  nonVegBasic: {
    mon: {
      breakfast: ["Chicken Maggi"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "chana Sabji",
        "Kadhai Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Navratna Korma",
        "Chicken Do Pyaza",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    tues: {
      breakfast: ["Chicken Sandwich"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Bhindi Sabji",
        "Chicken Kasha",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Mixed Veg",
        "Egg Masala",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    wed: {
      breakfast: ["Masala Dosa", "Sambar", "Coconut Chutney"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Alu Sabji",
        "Egg Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Mushroom Masala",
        "Mutton Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    thurs: {
      breakfast: ["Dhokla", "Sweet Chutney"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Soyabean Masala",
        "Chilli Egg",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Chana Sabji",
        "Kadhai Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    friday: {
      breakfast: ["Puri", "Dum Aalo"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Navratna Korma",
        "Chicken Do Pyaza",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Bhindi Sabji",
        "Chicken Kasha",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    saturday: {
      breakfast: ["Chole", "Bhature"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Mixed Veg",
        "Egg Bhurji Masala",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "alu Sabji",
        "Egg Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
    sunday: {
      breakfast: ["Paw Bhaji"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Mushroom Masala",
        "Mutton Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Soyabean Masala",
        "Chilli Egg",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
      ],
    },
  },
  nonVegPremium: {
    mon: {
      breakfast: ["Chole", "Bhature", "Orange Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Mixed Veg",
        "Palakh Paneer",
        "Chicken Do Pyaza",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Makhani",
        "Muli Ki Sabji",
        "Matar Paneer",
        "Egg Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    tues: {
      breakfast: ["Pav Bhaji", "Mango Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Cabbagae Dum Aalo",
        "Mushroom Masala",
        "Chicken Masala",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Mixed Veg",
        "Chana Sabji",
        "Reshmi Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    wed: {
      breakfast: ["Chole", "Kulche", "Pineapple Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Gobi Aalo",
        "Butter Paneer",
        "Egg Kasha",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Makhani",
        "Alu Matar",
        "Reshmi Paneer",
        "Mutton Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    thurs: {
      breakfast: ["Cheese Dosa", "Orange Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Alu Palakh",
        "Mushroom Masala",
        "Butter Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Mixed Veg",
        "Palakh Paneer",
        "Chicken Do Pyaza",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    friday: {
      breakfast: ["Chicken Sandwich", "Mango Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Muli ki Sabji",
        "Matar Paneer",
        "Egg Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Makhani",
        "Cabbage Dum Aalo",
        "Mushroom Masala",
        "Mutton Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    saturday: {
      breakfast: ["Chicken Maggi", "Pineapple Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Alu Mix Veg",
        "Chana Sabji",
        "Reshmi Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Tadka",
        "Gobi Aalo",
        "Butter Paneer",
        "Egg Kasha",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
    sunday: {
      breakfast: ["Aalo Paratha", "ketchup", "Orange Juice"],
      lunch: [
        "Rice/Roti",
        "Dal Fry",
        "Alu Matar",
        "Reshmi Paneer",
        "Mutton Curry",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Rasgulla",
      ],
      dinner: [
        "Rice/Roti",
        "Dal Makhani",
        "Alu Palakh",
        "Mushroom Masala",
        "Butter Chicken",
        "Papad/Salad",
        "Chutney",
        "Curd/Raita",
        "Gulab Jamun",
      ],
    },
  },
};

export default allPlansMealData;
